-- ─────────────────────────────────────────────────────────────
-- More curated Bible Learning resources
-- BibleProject + WVBS expansion pack
-- ─────────────────────────────────────────────────────────────

-- ─── BibleProject (more videos) ──────────────────────────────
INSERT INTO public.media_resources
(title, description, provider, category, resource_type, embed_url, external_url, thumbnail_url, speaker, tags, featured, sort_order) VALUES

('Heaven & Earth',
 'How the Bible''s story is about heaven and earth coming together — God''s plan to fully reunite the two.',
 'bibleproject', 'video', 'website',
 NULL,
 'https://bibleproject.com/explore/video/heaven-earth/',
 'https://bibleproject.com/downloads/heaven-earth/',
 'BibleProject', ARRAY['theme','kingdom of god'], true, 50),

('Image of God',
 'What it means that humans are made in the image of God, and why every person carries dignity.',
 'bibleproject', 'video', 'website',
 NULL,
 'https://bibleproject.com/explore/video/image-of-god/',
 NULL,
 'BibleProject', ARRAY['theme','humanity'], false, 60),

('The Holy Spirit',
 'Who the Holy Spirit is in the Bible and how he works in the life of every believer.',
 'bibleproject', 'video', 'website',
 NULL,
 'https://bibleproject.com/explore/video/holy-spirit/',
 NULL,
 'BibleProject', ARRAY['theme','holy spirit'], false, 70),

('Gospel of John Overview',
 'A two-part animated overview of John''s gospel — Jesus as the Word, the Light, and the Life.',
 'bibleproject', 'video', 'website',
 NULL,
 'https://bibleproject.com/explore/video/john/',
 NULL,
 'BibleProject', ARRAY['new testament','gospels'], true, 80),

('Gospel of Mark Overview',
 'Animated overview of Mark''s fast-paced account of Jesus — the suffering, serving Messiah.',
 'bibleproject', 'video', 'website',
 NULL,
 'https://bibleproject.com/explore/video/mark/',
 NULL,
 'BibleProject', ARRAY['new testament','gospels'], false, 81),

('Gospel of Luke Overview',
 'Overview of Luke''s gospel — Jesus as the saviour for the outsider and the broken.',
 'bibleproject', 'video', 'website',
 NULL,
 'https://bibleproject.com/explore/video/luke/',
 NULL,
 'BibleProject', ARRAY['new testament','gospels'], false, 82),

('Romans Overview',
 'Paul''s letter to the Romans — the gospel of God''s righteousness for Jew and Gentile.',
 'bibleproject', 'video', 'website',
 NULL,
 'https://bibleproject.com/explore/video/romans-1-4/',
 NULL,
 'BibleProject', ARRAY['new testament','letters'], false, 90),

('Psalms Overview',
 'How the book of Psalms is designed to shape your prayer life and your view of God.',
 'bibleproject', 'video', 'website',
 NULL,
 'https://bibleproject.com/explore/video/psalms/',
 NULL,
 'BibleProject', ARRAY['old testament','prayer','poetry'], false, 91),

('Word Study: Hesed (Loyal Love)',
 'BibleProject word study on "hesed" — the steadfast, loyal love of God.',
 'bibleproject', 'video', 'website',
 NULL,
 'https://bibleproject.com/explore/video/loyal-love/',
 NULL,
 'BibleProject', ARRAY['word study','love'], false, 92),

('Sabbath',
 'Why Sabbath rest matters and what it means for followers of Jesus today.',
 'bibleproject', 'video', 'website',
 NULL,
 'https://bibleproject.com/explore/video/sabbath/',
 NULL,
 'BibleProject', ARRAY['theme','rest'], false, 93),

-- ─── WVBS (more videos) ──────────────────────────────────────
('WVBS: Travel Through the Bible',
 'A tour of the Bible''s storyline from Genesis to Revelation, lesson by lesson.',
 'wvbs', 'video', 'website',
 NULL,
 'https://video.wvbs.org/category/travel-through-the-bible/',
 NULL,
 'WVBS', ARRAY['overview','series'], true, 30),

('WVBS: The Bible Project Overview',
 'A free WVBS video series walking through the whole Bible book by book.',
 'wvbs', 'video', 'website',
 NULL,
 'https://video.wvbs.org/category/all-videos/',
 NULL,
 'WVBS', ARRAY['series','overview'], false, 31),

('WVBS: Walking With Jesus',
 'A discipleship video series for new believers — learning to walk daily with Christ.',
 'wvbs', 'video', 'website',
 NULL,
 'https://walkingwith.wvbs.org/courses/walking-with-jesus/',
 NULL,
 'WVBS', ARRAY['discipleship','new believer'], true, 32),

('WVBS: The Christian Home',
 'Biblical teaching on marriage, parenting, and building a Christ-centered family.',
 'wvbs', 'video', 'website',
 NULL,
 'https://walkingwith.wvbs.org/courses/the-christian-home/',
 NULL,
 'WVBS', ARRAY['family','marriage'], false, 33),

('WVBS: Evidences for Christianity',
 'A video series presenting the historical and rational case for the Christian faith.',
 'wvbs', 'video', 'website',
 NULL,
 'https://walkingwith.wvbs.org/courses/evidences-for-christianity/',
 NULL,
 'WVBS', ARRAY['apologetics','evidences'], false, 34),

('WVBS: Old Testament Survey',
 'A book-by-book survey of the Old Testament with maps, timelines, and historical context.',
 'wvbs', 'course', 'website',
 NULL,
 'https://walkingwith.wvbs.org/courses/old-testament-survey/',
 NULL,
 'WVBS', ARRAY['old testament','survey'], false, 35),

('WVBS: New Testament Survey',
 'A book-by-book survey of the New Testament — the gospels, Acts, letters, and Revelation.',
 'wvbs', 'course', 'website',
 NULL,
 'https://walkingwith.wvbs.org/courses/new-testament-survey/',
 NULL,
 'WVBS', ARRAY['new testament','survey'], false, 36);
