// ============================================================
// ChurchFlow Liberia — Documentation Page (/docs)
// ============================================================
import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import {
  BookOpen, Users, CalendarCheck, DollarSign, CalendarDays,
  BarChart2, Code2, HelpCircle, ChevronRight, Rocket,
  Building2, UserPlus, ListChecks, CheckCircle2
} from 'lucide-react'
import PublicLayout from './PublicLayout'

const SIDEBAR_SECTIONS = [
  {
    label: 'Getting Started',
    icon: Rocket,
    items: [
      { label: 'Introduction',            anchor: 'intro'        },
      { label: 'Create your account',     anchor: 'create'       },
      { label: 'Set up church profile',   anchor: 'profile'      },
      { label: 'Add your first members',  anchor: 'members'      },
      { label: 'Record attendance',       anchor: 'attendance'   },
      { label: 'Add first offering',      anchor: 'offering'     },
    ],
  },
  {
    label: 'Members',
    icon: Users,
    items: [
      { label: 'Member profiles',         anchor: 'member-profiles'    },
      { label: 'Departments',             anchor: 'member-departments' },
      { label: 'Import members (CSV)',    anchor: 'member-import'      },
    ],
  },
  {
    label: 'Attendance',
    icon: CalendarCheck,
    items: [
      { label: 'Record attendance',       anchor: 'att-record'  },
      { label: 'QR code check-in',        anchor: 'att-qr'      },
      { label: 'Service types',           anchor: 'att-types'   },
    ],
  },
  {
    label: 'Finance',
    icon: DollarSign,
    items: [
      { label: 'Record offerings',        anchor: 'fin-offerings' },
      { label: 'Categories',              anchor: 'fin-cats'      },
      { label: 'Export reports',          anchor: 'fin-export'    },
    ],
  },
  {
    label: 'Events',
    icon: CalendarDays,
    items: [
      { label: 'Create an event',         anchor: 'evt-create'  },
      { label: 'RSVP and registration',   anchor: 'evt-rsvp'    },
    ],
  },
  {
    label: 'Reports',
    icon: BarChart2,
    items: [
      { label: 'Analytics dashboard',     anchor: 'rep-dash'    },
      { label: 'Export PDF / Excel',      anchor: 'rep-export'  },
    ],
  },
  {
    label: 'API',
    icon: Code2,
    items: [
      { label: 'Authentication',          anchor: 'api-auth'    },
      { label: 'Endpoints overview',      anchor: 'api-overview'},
    ],
  },
  {
    label: 'FAQs',
    icon: HelpCircle,
    items: [
      { label: 'Frequently asked questions', anchor: 'faq'      },
    ],
  },
]

const GETTING_STARTED_STEPS = [
  {
    number: '01',
    icon: Building2,
    title: 'Create Your Church Account',
    anchor: 'create',
    content: `Navigate to churchflow.lr and click "Get Started". You will be asked to enter your church name, denomination, city, country, and an admin email address. A verification email will be sent to confirm your account. Once verified, you are in.`,
    code: null,
    tip: 'Use an email address that your church leadership team can access — this will be the primary admin account.',
  },
  {
    number: '02',
    icon: Building2,
    title: 'Set Up Your Church Profile',
    anchor: 'profile',
    content: `After logging in for the first time, you will be guided through the church profile setup wizard. Provide your church logo, address, service schedule, default currency (LRD or USD), and time zone. These details appear on all reports and receipts generated by ChurchFlow.`,
    code: null,
    tip: 'Take 5 minutes to fill in all profile fields completely. This information pre-fills receipts and reports, saving you time every month.',
  },
  {
    number: '03',
    icon: UserPlus,
    title: 'Add Your First Members',
    anchor: 'members',
    content: `Go to the Members module from the sidebar. Click "Add Member" to create an individual profile. Fill in: full name, phone number, email (optional), date of birth, gender, joining date, department, baptism status, and membership status. You can also bulk-import members using a CSV file by clicking "Import".`,
    code: `// CSV format for bulk import
Name, Phone, Email, Gender, DOB, Department, Status
Samuel Kollie, +231770001234, s@example.com, Male, 1990-05-10, Choir, Active
Grace Flomo, +231770005678, , Female, 1985-08-22, Ushers, Active`,
    tip: 'Start with your key leaders and department heads so you can assign roles immediately.',
  },
  {
    number: '04',
    icon: CalendarCheck,
    title: 'Record Your First Attendance',
    anchor: 'attendance',
    content: `Open the Attendance module and click "New Attendance Record". Select the service type (Sunday Service, Mid-week, Youth, etc.), the date, and the branch. You can then mark attendance by ticking member names from the list, or scanning QR codes if members have their codes printed or saved. Hit "Save Record" when done.`,
    code: null,
    tip: 'Assign a department leader to take attendance for their group — this distributes the work and improves accuracy.',
  },
  {
    number: '05',
    icon: DollarSign,
    title: 'Add Your First Offering',
    anchor: 'offering',
    content: `Go to the Finance module and click "Record Offering". Select the offering category (Tithe, Building Fund, Special, Missions, etc.), enter the amount, select the currency (LRD or USD), and add any notes. ChurchFlow will automatically generate a receipt number and timestamp the record. You can also record envelope-based offerings by entering the envelope number and member name.`,
    code: null,
    tip: 'Set up all your offering categories before recording the first Sunday so reports are properly categorised from day one.',
  },
]

const FAQ_ITEMS = [
  {
    q: 'Can I use ChurchFlow on my phone?',
    a: 'Yes. ChurchFlow is a Progressive Web App. Open your browser, navigate to the app, and select "Add to Home Screen" to install it like a native app on any Android or iPhone device.',
  },
  {
    q: 'Does ChurchFlow work without internet?',
    a: 'Core features like member lookup and attendance marking have limited offline capability. Full offline support is included in the roadmap for a future release. For best results, use on a stable data connection.',
  },
  {
    q: 'How do I add a second branch?',
    a: 'Go to Settings, then Branches, and click "Add Branch". Assign a branch administrator and they will receive an invitation email to manage their branch dashboard.',
  },
  {
    q: 'Can I export all my data?',
    a: 'Yes. From Settings, navigate to "Data & Privacy" and select "Export All Data". You will receive a ZIP file containing all your church records in both CSV and PDF format.',
  },
  {
    q: 'How do I reset my password?',
    a: 'On the login page, click "Forgot password?" and enter your admin email. You will receive a password reset link within a few minutes.',
  },
]

export default function DocumentationPage() {
  const [activeSection, setActiveSection] = useState('intro')

  return (
    <PublicLayout>
      {/* Hero */}
      <section className="bg-gradient-to-br from-[#1E1B4B] to-[#312e81] py-14 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center gap-2 text-purple-300 text-sm mb-3">
            <Link to="/landing" className="hover:text-white transition-colors">Home</Link>
            <ChevronRight className="w-3.5 h-3.5" />
            <span className="text-white">Documentation</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white mb-3">Documentation</h1>
          <p className="text-purple-200 text-base max-w-xl">
            Everything you need to get the most out of ChurchFlow. Guides, references, and FAQs.
          </p>
        </div>
      </section>

      {/* Doc layout */}
      <div className="max-w-7xl mx-auto px-4 py-12 flex flex-col lg:flex-row gap-10">

        {/* Sidebar */}
        <aside className="w-full lg:w-64 flex-shrink-0">
          <nav className="lg:sticky lg:top-20 space-y-6">
            {SIDEBAR_SECTIONS.map(section => {
              const Icon = section.icon
              return (
                <div key={section.label}>
                  <div className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">
                    <Icon className="w-3.5 h-3.5" />
                    {section.label}
                  </div>
                  <ul className="space-y-0.5 pl-1">
                    {section.items.map(item => (
                      <li key={item.anchor}>
                        <a
                          href={`#${item.anchor}`}
                          onClick={() => setActiveSection(item.anchor)}
                          className={`block px-3 py-2 rounded-lg text-sm transition-colors ${
                            activeSection === item.anchor
                              ? 'bg-purple-50 text-[#7C3AED] font-semibold'
                              : 'text-slate-600 hover:text-[#7C3AED] hover:bg-slate-50'
                          }`}
                        >
                          {item.label}
                        </a>
                      </li>
                    ))}
                  </ul>
                </div>
              )
            })}
          </nav>
        </aside>

        {/* Main content */}
        <main className="flex-1 min-w-0">

          {/* Intro */}
          <div id="intro" className="mb-12">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-xl bg-purple-100 flex items-center justify-center">
                <BookOpen className="w-5 h-5 text-[#7C3AED]" />
              </div>
              <div>
                <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">Getting Started</p>
                <h2 className="text-2xl font-extrabold text-[#1E1B4B]">Getting Started with ChurchFlow</h2>
              </div>
            </div>
            <p className="text-slate-600 leading-relaxed mb-4">
              Welcome to ChurchFlow Liberia. This guide will walk you through everything you need to do to have your church fully set up and running on ChurchFlow. From creating your account to recording your first offering, follow each step in order for the smoothest onboarding experience.
            </p>
            <div className="flex flex-wrap gap-3">
              {['5 setup steps', '~15 minutes', 'No technical knowledge required'].map(tag => (
                <span key={tag} className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-purple-50 text-[#7C3AED] rounded-full text-xs font-semibold">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  {tag}
                </span>
              ))}
            </div>
          </div>

          {/* Steps */}
          <div className="space-y-12">
            {GETTING_STARTED_STEPS.map((step, idx) => {
              const Icon = step.icon
              return (
                <div key={step.anchor} id={step.anchor} className="scroll-mt-20">
                  <div className="flex items-start gap-4 mb-5">
                    <div className="w-10 h-10 rounded-full bg-gradient-to-br from-[#7C3AED] to-violet-700 flex items-center justify-center text-white font-black text-sm flex-shrink-0 shadow">
                      {step.number}
                    </div>
                    <div>
                      <h3 className="text-xl font-bold text-[#1E1B4B]">{step.title}</h3>
                    </div>
                  </div>

                  <div className="ml-14">
                    <p className="text-slate-600 leading-relaxed mb-5">{step.content}</p>

                    {step.code && (
                      <div className="bg-[#1E1B4B] rounded-xl overflow-hidden mb-5">
                        <div className="flex items-center justify-between px-4 py-2 bg-white/5 border-b border-white/10">
                          <span className="text-xs text-slate-400 font-mono">Example</span>
                        </div>
                        <pre className="p-4 text-xs text-green-300 font-mono leading-relaxed overflow-x-auto whitespace-pre-wrap">
                          {step.code}
                        </pre>
                      </div>
                    )}

                    {step.tip && (
                      <div className="flex items-start gap-3 p-4 bg-amber-50 rounded-xl border border-amber-200">
                        <ListChecks className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
                        <div>
                          <p className="text-xs font-bold text-amber-700 uppercase tracking-wider mb-1">Tip</p>
                          <p className="text-amber-700 text-sm leading-relaxed">{step.tip}</p>
                        </div>
                      </div>
                    )}

                    {idx < GETTING_STARTED_STEPS.length - 1 && (
                      <div className="mt-8 pt-8 border-t border-slate-100" />
                    )}
                  </div>
                </div>
              )
            })}
          </div>

          {/* FAQ */}
          <div id="faq" className="mt-16 scroll-mt-20">
            <h2 className="text-2xl font-extrabold text-[#1E1B4B] mb-8">Frequently Asked Questions</h2>
            <div className="space-y-6">
              {FAQ_ITEMS.map(item => (
                <div key={item.q} className="border-b border-slate-100 pb-6 last:border-0">
                  <h4 className="font-bold text-[#1E1B4B] mb-2 flex items-start gap-2">
                    <HelpCircle className="w-4 h-4 text-[#7C3AED] flex-shrink-0 mt-0.5" />
                    {item.q}
                  </h4>
                  <p className="text-slate-600 text-sm leading-relaxed pl-6">{item.a}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Footer nav */}
          <div className="mt-16 pt-8 border-t border-slate-200 flex flex-col sm:flex-row justify-between gap-4">
            <Link
              to="/help"
              className="flex items-center gap-2 text-sm text-[#7C3AED] font-semibold hover:underline"
            >
              Visit Help Centre
              <ChevronRight className="w-4 h-4" />
            </Link>
            <Link
              to="/contact"
              className="flex items-center gap-2 text-sm text-[#7C3AED] font-semibold hover:underline"
            >
              Contact Support
              <ChevronRight className="w-4 h-4" />
            </Link>
          </div>
        </main>
      </div>
    </PublicLayout>
  )
}
